"""media in postgres

Revision ID: f15329817b05
Revises: fe7930865b47
Create Date: 2026-10-05 17:57:06.610043

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f15329817b05"
down_revision: str | Sequence[str] | None = "fe7930865b47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.String(length=40), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("messages", sa.Column("media_id", sa.String(length=64), nullable=True))
    op.create_foreign_key("messages_media_id_fkey", "messages", "media", ["media_id"], ["id"])
    op.drop_column("messages", "media_path")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages", sa.Column("media_path", sa.VARCHAR(length=300), autoincrement=False, nullable=True)
    )
    op.drop_constraint("messages_media_id_fkey", "messages", type_="foreignkey")
    op.drop_column("messages", "media_id")
    op.drop_table("media")
    # ### end Alembic commands ###
